describe('Negative Cases - Registro de Usuario', {testIsolation : false},() => {

  const url = 'https://ticketazo.com.ar/auth/registerUser';

  // Caso 1: Registro fallido por campos vacíos
it('Registro fallido Campo Nombre Vacio', () => {
     cy.visit(url)
     cy.contains('Nombres').should('exist')
     cy.get('[data-cy="input-apellido"]').type('Cosa')
     cy.get('[data-cy="input-telefono"]').type('0123456789')
     cy.get('[data-cy="input-dni"]').type('10045678')
     cy.get('[data-cy="select-provincia"]').click().type('Entre Rios{enter}')
     cy.get('[data-cy="select-localidad"]').click().type('Concordia{enter}')
     cy.contains('dd').type('05')
     cy.contains('mm').type('08')
     cy.contains('aaaa').type('1990')
     cy.get('[data-cy="input-email"]').type ('algo@gm.com')
     cy.get('[data-cy="input-confirmar-email"]').type('algo@gm.com')
     cy.get('[data-cy="input-password"]').type('1234Abcd/')
     cy.get('[data-cy="input-repetir-password"]').type('1234Abcd/')
     cy.get('[data-cy="btn-registrarse"]').click()
     cy.get('[data-focus-within="true"] > .hidden').contains('Rellene este campo').and('be.visible') 

}) 
it('Registro fallido Campo Apellido Vacio', () => {
     cy.visit(url)
     cy.get('[data-cy="input-nombres"]').type('juan Pedro')
     cy.contains('Apellido').should('exist')
     cy.get('[data-cy="input-telefono"]').type('0123456789')
     cy.get('[data-cy="input-dni"]').type('10045678')
     cy.get('[data-cy="select-provincia"]').click().type('Entre Rios{enter}')
     cy.get('[data-cy="select-localidad"]').click().type('Concordia{enter}')
     cy.contains('dd').type('05')
     cy.contains('mm').type('08')
     cy.contains('aaaa').type('1990')
     cy.get('[data-cy="input-email"]').type ('algo@gm.com')
     cy.get('[data-cy="input-confirmar-email"]').type('algo@gm.com')
     cy.get('[data-cy="input-password"]').type('1234Abcd/')
     cy.get('[data-cy="input-repetir-password"]').type('1234Abcd/')
     cy.get('[data-cy="btn-registrarse"]').click()
     cy.get('[data-invalid="true"] > .hidden').contains('Rellene este campo').and('be.visible')


})
it('Registro fallido Campo Telefono Vacio', () => {
     cy.visit(url)
     cy.get('[data-cy="input-nombres"]').type('juan Pedro')
     cy.get('[data-cy="input-apellido"]').type('Coso')
     cy.contains('Teléfono').should('exist')
     cy.get('[data-cy="input-dni"]').type('10045678')
     cy.get('[data-cy="select-provincia"]').click().type('Entre Rios{enter}')
     cy.get('[data-cy="select-localidad"]').click().type('Concordia{enter}')
     cy.contains('dd').type('05')
     cy.contains('mm').type('08')
     cy.contains('aaaa').type('1990')
     cy.get('[data-cy="input-email"]').type ('algo@gm.com')
     cy.get('[data-cy="input-confirmar-email"]').type('algo@gm.com')
     cy.get('[data-cy="input-password"]').type('1234Abcd/')
     cy.get('[data-cy="input-repetir-password"]').type('1234Abcd/')
     cy.get('[data-cy="btn-registrarse"]').click()
    cy.get('[data-invalid="true"] > .hidden').contains('Rellene este campo').and('be.visible')

})
it('Registro fallido Campo dni Vacio', () => {
     cy.visit(url)
     cy.get('[data-cy="input-nombres"]').type('juan Pedro')
     cy.get('[data-cy="input-apellido"]').type('Coso')
     cy.get('[data-cy="input-telefono"]').type('0123456789')
     cy.contains('DNI').should('exist')
     cy.get('[data-cy="select-provincia"]').click().type('Entre Rios{enter}')
     cy.get('[data-cy="select-localidad"]').click().type('Concordia{enter}')
     cy.contains('dd').type('05')
     cy.contains('mm').type('08')
     cy.contains('aaaa').type('1990')
     cy.get('[data-cy="input-email"]').type ('algo@gm.com')
     cy.get('[data-cy="input-confirmar-email"]').type('algo@gm.com')
     cy.get('[data-cy="input-password"]').type('1234Abcd/')
     cy.get('[data-cy="input-repetir-password"]').type('1234Abcd/')
     cy.get('[data-cy="btn-registrarse"]').click()
    cy.get('[data-invalid="true"] > .hidden').contains('Rellene este campo').and('be.visible')
})
it('Registro fallido Campo Provincia Vacio', () => {
      cy.visit(url)
     cy.get('[data-cy="input-nombres"]').type('juan Pedro')
     cy.get('[data-cy="input-apellido"]').type('Coso')
     cy.get('[data-cy="input-telefono"]').type('0123456789')
     cy.get('[data-cy="input-dni"]').type('10045678')
     cy.contains('Provincia').should('exist')
     cy.get('[data-cy="select-localidad"]').click().type('Concordia{enter}')
     cy.contains('dd').type('05')
     cy.contains('mm').type('08')
     cy.contains('aaaa').type('1990')
     cy.get('[data-cy="input-email"]').type ('algo@gm.com')
     cy.get('[data-cy="input-confirmar-email"]').type('algo@gm.com')
     cy.get('[data-cy="input-password"]').type('1234Abcd/')
     cy.get('[data-cy="input-repetir-password"]').type('1234Abcd/')
     cy.get('[data-cy="btn-registrarse"]').click()
     cy.get('[data-invalid="true"] > .hidden').contains('Rellene este campo').and('be.visible')
})
it('Registro fallido Campo Localidad Vacio', () => {
     cy.visit(url)
     cy.get('[data-cy="input-nombres"]').type('juan Pedro') 
      cy.get('[data-cy="input-apellido"]').type('Coso')
      cy.get('[data-cy="input-telefono"]').type('0123456789')
      cy.get('[data-cy="input-dni"]').type('10045678')
      cy.get('[data-cy="select-provincia"]').click().type('Entre Rios{enter}')
      cy.contains('Localidad').should('exist')  
      cy.contains('dd').type('05')
      cy.contains('mm').type('08')
      cy.contains('aaaa').type('1990')  
      cy.get('[data-cy="input-email"]').type ('algo@gm.com')
     cy.get('[data-cy="input-confirmar-email"]').type('algo@gm.com')
     cy.get('[data-cy="input-password"]').type('1234Abcd/')
     cy.get('[data-cy="input-repetir-password"]').type('1234Abcd/')
     cy.get('[data-cy="btn-registrarse"]').click()
     cy.get('[data-invalid="true"] > .hidden').contains('Rellene este campo').and('be.visible')
})
it('Registro fallido Campo Dia de Nacimiento Vacio', () => {
     cy.visit(url)
     cy.get('[data-cy="input-nombres"]').type('juan Pedro') 
      cy.get('[data-cy="input-apellido"]').type('Coso')
      cy.get('[data-cy="input-telefono"]').type('0123456789')
      cy.get('[data-cy="input-dni"]').type('10045678')
      cy.get('[data-cy="select-provincia"]').click().type('Entre Rios{enter}')
      cy.get('[data-cy="select-localidad"]').click().type('Concordia{enter}')
      cy.contains('dd').should('exist')  
      cy.contains('mm').type('08')
      cy.contains('aaaa').type('1990')  
      cy.get('[data-cy="input-email"]').type ('algo@gm.com')
     cy.get('[data-cy="input-confirmar-email"]').type('algo@gm.com')
     cy.get('[data-cy="input-password"]').type('1234Abcd/')
     cy.get('[data-cy="input-repetir-password"]').type('1234Abcd/')
     cy.get('[data-cy="btn-registrarse"]').click()
     cy.get('[data-invalid="true"] > .hidden').contains('Rellene este campo').and('be.visible')
})
it('Registro fallido Campo Mes de Nacimiento vacio', () => {
     cy.visit(url)
     cy.get('[data-cy="input-nombres"]').type('juan Pedro') 
     cy.get('[data-cy="input-apellido"]').type('Coso')
     cy.get('[data-cy="input-telefono"]').type('0123456789')   
     cy.get('[data-cy="input-dni"]').type('10045678')    
     cy.get('[data-cy="select-provincia"]').click().type('Entre Rios{enter}')
     cy.get('[data-cy="select-localidad"]').click().type('Concordia{enter}')
     cy.contains('dd').type('05')
     cy.contains('mm').should('exist')  
     cy.contains('aaaa').type('1990')  
     cy.get('[data-cy="input-email"]').type ('algo@gm.com')
     cy.get('[data-cy="input-confirmar-email"]').type('algo@gm.com')
     cy.get('[data-cy="input-password"]').type('1234Abcd/')
     cy.get('[data-cy="input-repetir-password"]').type('1234Abcd/')
     cy.get('[data-cy="btn-registrarse"]').click()
     cy.get('[data-invalid="true"] > .hidden').contains('Rellene este campo').and('be.visible')
})
it('Registro fallido Campo Año de Nacimiento vacio', () => {
     cy.visit(url)  
     cy.get('[data-cy="input-nombres"]').type('juan Pedro')
     cy.get('[data-cy="input-apellido"]').type('Coso')
     cy.get('[data-cy="input-telefono"]').type('0123456789')
     cy.get('[data-cy="input-dni"]').type('10045678')
     cy.get('[data-cy="select-provincia"]').click().type('Entre Rios{enter}')
     cy.get('[data-cy="select-localidad"]').click().type('Concordia{enter}')
     cy.contains('dd').type('05')
     cy.contains('mm').type('08')
     cy.contains('aaaa').should('exist')  
     cy.get('[data-cy="input-email"]').type ('algo@gm.com')
     cy.get('[data-cy="input-confirmar-email"]').type('algo@gm.com')
     cy.get('[data-cy="input-password"]').type('1234Abcd/')
     cy.get('[data-cy="input-repetir-password"]').type('1234Abcd/')
     cy.get('[data-cy="btn-registrarse"]').click()
     cy.get('[data-invalid="true"] > .hidden').contains('Rellene este campo').and('be.visible')
})
it('Registro fallido Campo Email Vacio', () => {
     cy.visit(url)
     cy.get('[data-cy="input-nombres"]').type('juan Pedro')   
     cy.get('[data-cy="input-apellido"]').type('Coso')      
     cy.get('[data-cy="input-telefono"]').type('0123456789')
     cy.get('[data-cy="input-dni"]').type('10045678')
      cy.get('[data-cy="select-provincia"]').click().type('Entre Rios{enter}')
      cy.get('[data-cy="select-localidad"]').click().type('Concordia{enter}')
      cy.contains('dd').type('05')
      cy.contains('mm').type('08')
      cy.contains('aaaa').type('1990')  
     cy.contains('Email').should('exist')
     cy.get('[data-cy="input-confirmar-email"]').type('algo@gm.com')
     cy.get('[data-cy="input-password"]').type('1234Abcd/')
     cy.get('[data-cy="input-repetir-password"]').type('1234Abcd/')
     cy.get('[data-cy="btn-registrarse"]').click()
     cy.get('[data-invalid="true"] > .hidden').contains('Rellene este campo').and('be.visible')
})
it('Registro fallido Campo Confirmar Email Vacio', () => { 
      cy.visit(url)   
      cy.get('[data-cy="input-nombres"]').type('juan Pedro')
      cy.get('[data-cy="input-apellido"]').type('Coso')
      cy.get('[data-cy="input-telefono"]').type('0123456789')
      cy.get('[data-cy="input-dni"]').type('10045678')
      cy.get('[data-cy="select-provincia"]').click().type('Entre Rios{enter}')
      cy.get('[data-cy="select-localidad"]').click().type('Concordia{enter}')
      cy.contains('dd').type('05')
      cy.contains('mm').type('08')
      cy.contains('aaaa').type('1990')
      cy.get('[data-cy="input-email"]').type ('algo@gm.com')  
      cy.contains('Confirmar Email').should('exist')
      cy.get('[data-cy="input-password"]').type('1234Abcd/')
      cy.get('[data-cy="input-repetir-password"]').type('1234Abcd/')
      cy.get('[data-cy="btn-registrarse"]').click()
      cy.get('[data-invalid="true"] > .hidden').contains('Rellene este campo').and('be.visible')
})
it('Registro fallido Campo Contraseña Vacio', () => {
     cy.visit(url)
     cy.get('[data-cy="input-nombres"]').type('juan Pedro') 
      cy.get('[data-cy="input-apellido"]').type('Coso')
      cy.get('[data-cy="input-telefono"]').type('0123456789')
      cy.get('[data-cy="input-dni"]').type('10045678')
      cy.get('[data-cy="select-provincia"]').click().type('Entre Rios{enter}')
      cy.get('[data-cy="select-localidad"]').click().type('Concordia{enter}')
      cy.contains('dd').type('05')
      cy.contains('mm').type('08')
      cy.contains('aaaa').type('1990')  
     cy.get('[data-cy="input-email"]').type ('algo@gm.com')
     cy.get('[data-cy="input-confirmar-email"]').type('algo@gm.com ') 
      cy.contains('Contraseña').should('exist') 
      cy.get('[data-cy="input-repetir-password"]').type('1234Abcd/')
      cy.get('[data-cy="btn-registrarse"]').click()
      cy.get('[data-invalid="true"] > .hidden').contains('Rellene este campo').and('be.visible')
})
it('Registro fallido Campo Repetir Contraseña Vacio', () => {
     cy.visit(url)
     cy.get('[data-cy="input-nombres"]').type('juan Pedro')
      cy.get('[data-cy="input-apellido"]').type('Coso')
      cy.get('[data-cy="input-telefono"]').type('0123456789')
      cy.get('[data-cy="input-dni"]').type('10045678')
      cy.get('[data-cy="select-provincia"]').click().type('Entre Rios{enter}')
      cy.get('[data-cy="select-localidad"]').click().type('Concordia{enter}')
      cy.contains('dd').type('05')
      cy.contains('mm').type('08')
      cy.contains('aaaa').type('1990')  
     cy.get('[data-cy="input-email"]').type ('algo@gm.com')
     cy.get('[data-cy="input-confirmar-email"]').type('algo@gm.com ') 
      cy.get('[data-cy="input-password"]').type('1234Abcd/')
      cy.contains('Repetir Contraseña').should('exist')
      cy.get('[data-cy="btn-registrarse"]').click()
      cy.get('[data-invalid="true"] > .hidden').contains('Rellene este campo').and('be.visible')
})

  // Caso 2: Los correos electronicos no coinciden
it('Registro fallido por correos diferentes', () => {
     cy.visit(url)
     cy.get('[data-cy="input-nombres"]').type('juan Pedro')
     cy.get('[data-cy="input-apellido"]').type('Coso')
     cy.get('[data-cy="input-telefono"]').type('0123456789')
     cy.get('[data-cy="input-dni"]').type('10045678')
     cy.get('[data-cy="select-provincia"]').click().type('Entre Rios{enter}')
     cy.get('[data-cy="select-localidad"]').click().type('Concordia{enter}')
     cy.contains('dd').type('05')
     cy.contains('mm').type('08')
     cy.contains('aaaa').type('1990')
     cy.get('[data-cy="input-email"]').type ('algo@gm.com')
     cy.get('[data-cy="input-confirmar-email"]').type('difalgo@gm.com')
     cy.get('[data-cy="input-password"]').type('1234Abcd/')
     cy.get('[data-cy="input-repetir-password"]').type('1234Abcd/')
     cy.get('[data-cy="btn-registrarse"]').click()
     cy.get('[data-cy="error-message"]').contains('Los correos electrónicos no coinciden').and('be.visible') 
})
     
 // Caso 3: Teléfono inválido  
it('No permite registrarse con un teléfono inválido', () => {
    cy.visit(url)
    cy.get('[data-cy="input-telefono"]').type('abcde12345')
    cy.get('[data-cy="btn-registrarse"]').click()
    cy.get('.group.is-filled > .hidden').contains('Ajústese al formato solicitado: Número de teléfono de 10 dígitos.').and('be.visible')
  })

  // Caso 4: Contraseñas invalidas
it('Registro fallido por contraseñas invalidas', () => {
    cy.visit(url)
     cy.get('[data-cy="input-nombres"]').type('juan Pedro')
     cy.get('[data-cy="input-apellido"]').type('Coso')
     cy.get('[data-cy="input-telefono"]').type('0123456789')
     cy.get('[data-cy="input-dni"]').type('10045678')
     cy.get('[data-cy="select-provincia"]').click().type('Entre Rios{enter}')
     cy.get('[data-cy="select-localidad"]').click().type('Concordia{enter}')
     cy.contains('dd').type('05')
     cy.contains('mm').type('08')
     cy.contains('aaaa').type('1990')
     cy.get('[data-cy="input-email"]').type ('algo@gm.com')
     cy.get('[data-cy="input-confirmar-email"]').type('algo@gm.com')
    cy.get('[data-cy="input-password"]').type('1234Abcd/')
    cy.get('[data-cy="input-repetir-password"]').type('abcd1234/')
    cy.get('[data-cy="btn-registrarse"]').click() 
    cy.get('[data-cy="error-message"]').contains('Las contraseñas no coinciden').and('be.visible')
  
})

  // Caso 5: Email con formato inválido
 it('Registro fallido con un email inválido', () => {
    cy.visit(url)
    cy.get('[data-cy="input-email"]').type('algogm.com')
    cy.get('[data-cy="input-confirmar-email"]').type('algogm.com')
    cy.get('[data-cy="btn-registrarse"]').click()
    cy.contains('Introduzca una dirección de correo').should('exist')
    cy.get('[data-cy="btn-registrarse"]').click()

  })


  // Caso 6: DNI inválido
  it('Registro fallido por DNI inválido', () => {
   cy.visit(url)
   cy.get('[data-cy="input-dni"]').type('123')
    cy.get('[data-cy="btn-registrarse"]').click()
    cy.contains('Ajústese al formato solicitado: Número de DNI de 8 dígitos.').should('exist')

})

     

  

})